//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeekTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class answers
    {
        public int id { get; set; }
        public string answer { get; set; }
        public Nullable<int> parent_question { get; set; }
        public Nullable<bool> correct_answer { get; set; }
    }
}
