//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeekTest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tests
    {
        public int id { get; set; }
        [Display(Name="Название теста")]
        public string test_name { get; set; }
        [Display(Name = "Время (минут)")]
        public int duration { get; set; }
        [Display(Name = "Описание")]
        public string test_info { get; set; }
    }
}
